dataset:
  dataset_module: sacyr
  root: ./data/datasets
  num_workers: 4
  mode: reggresion  # classification
  kfold:
    num_folds: 5
    shuffle: True

scaler:
  name: quantil # standard

# model:
#   # name: mlp
#   # num_layers: 3
#   # hidden_size: 512
#   # activation: relu
#   # dropout: 0.3

#   name: periodical_mlp
#   num_layers: 3
#   hidden_size: 512
#   dropout: 0.3
#   d_embedding: 64
#   n_frequencies: 48
#   frequency_init_scale: 5

loss:
  name: mse

optimizer:
  name: adam
  lr: 0.001
  weight_decay: 0.0001
  scheduler: step
  step_size: 10
  gamma: 0.1

training:
  epochs: 1
  batch_size: 1024
  num_workers: 2
  prefetch_factor: 3
  seed: 42
  device: "cuda"
  log_dir: logs

scheduler:
   name: reduce_on_plateau
   patience: 5
   factor: 0.1

metrics:
  - name: mae
    prediction_horizon: 1

callbacks:
  - name: checkpoint
    dirpath: "checkpoints/"
    monitor: "Val_loss" # cap-sensitive
    mode: "min"
  - name: wandb_logger
    project: "sacyr"
    entity: "inaki"
  - name: early_stopping
    patience: 15
    monitor: "Val_loss"

wandb:
  project: "sacyr"
  entity: "inaki"
  dir: "wandb"
  log_plots: True
