program: main.py
method: bayes
metric:
  name: Val_loss_mean
  goal: minimize

parameters:
  dataset.name:
    values: ["108+43+3493-24h-1h-1c"] # 108+43-48h-1h-1c
    
  model.name:
    values: ["lstm"]

  scaler.name:
    values: ["quantil", "standard"]

  model.num_layers:
    min: 1
    max: 5
    distribution: int_uniform

  model.hidden_size:
    min: 128
    max: 1024
    distribution: int_uniform

  model.dropout:
    min: 0.1
    max: 0.5
