dataset:
  dataset_module: sacyr
  root: ./data/datasets
  num_workers: 4
  mode: reggresion
  kfold:
    num_folds: 5
    shuffle: true
  name: 139-24h-24h-3L-2c
scaler:
  name: standard
loss:
  name: mse
optimizer:
  name: adam
  lr: 0.001
  weight_decay: 0.0001
  scheduler: step
  step_size: 10
  gamma: 0.1
training:
  epochs: 100
  batch_size: 1024
  num_workers: 2
  prefetch_factor: 3
  seed: 42
  device: cuda
  log_dir: logs
scheduler:
  name: reduce_on_plateau
  patience: 5
  factor: 0.1
metrics:
- name: mae-sacyr-1h
  prediction_horizon: 1
callbacks:
- name: checkpoint
  dirpath: checkpoints/
  monitor: Val_loss
  mode: min
- name: wandb_logger
  project: sacyr
  entity: inaki
- name: early_stopping
  patience: 15
  monitor: Val_loss
wandb:
  project: sacyr
  entity: inaki
  dir: wandb
  log_plots: true
model:
  cnn_filters: 201
  dropout: 0.1730169040890261
  hidden_size: 865
  kernel_size: 3
  name: cnn_lstm
  num_layers: 1
experiment_id: 139-24h-24h-3L-2c_cnn_lstm_ee599e1c
